use const_crypto::ed25519;
use solana_program::pubkey::Pubkey;
use tape_crypto::address::Address;
use crate::program::metaplex;

tape_solana::declare_id!("Ksbh7JPYe9XX1Y18GDuNoVZBtMBiD5uyTPFN36dVW16");

pub const PROGRAM_ID: [u8; 32] = 
    unsafe { *(&id() as *const Pubkey as *const [u8; 32]) };
pub const METADATA_PROGRAM_ID: [u8; 32] = metaplex::PROGRAM_ID;

pub const MINT:      &[u8] = b"mint";
pub const MINT_SEED: &[u8] = &[152, 68, 212, 200, 25, 113, 221, 71];
pub const METADATA:  &[u8] = b"metadata";
pub const TREASURY:  &[u8] = b"treasury";

pub const TOKEN_DECIMALS: u8 = 9;
pub const ONE_TAPE: u64 = 10u64.pow(TOKEN_DECIMALS as u32);
pub const MAX_SUPPLY: u64 = 7_000_000 * ONE_TAPE;

pub const METADATA_NAME:   &str = "TAPE";
pub const METADATA_SYMBOL: &str = "TAPE";
pub const METADATA_URI:    &str = "https://tapedrive.io/metadata.json";

pub const MINT_ADDRESS: Address =
    Address::new(ed25519::derive_program_address(&[MINT, MINT_SEED], &PROGRAM_ID).0);

pub const MINT_BUMP: u8 = 
    ed25519::derive_program_address(&[MINT, MINT_SEED], &PROGRAM_ID).1;

pub const METADATA_ADDRESS: Address = Address::new(
    ed25519::derive_program_address(
        &[
            METADATA,
            &METADATA_PROGRAM_ID,
            MINT_ADDRESS.as_bytes(),
        ],
        &METADATA_PROGRAM_ID,
    ).0
);

pub const METADATA_BUMP: u8 = ed25519::derive_program_address(
    &[
        METADATA,
        &METADATA_PROGRAM_ID,
        MINT_ADDRESS.as_bytes(),
    ],
    &METADATA_PROGRAM_ID,
).1;

pub const TREASURY_ADDRESS: Address =
    Address::new(ed25519::derive_program_address(&[TREASURY], &PROGRAM_ID).0);

pub const TREASURY_BUMP: u8 =
    ed25519::derive_program_address(&[TREASURY], &PROGRAM_ID).1;


#[cfg(debug_assertions)]
pub fn mint_pda() -> (Address, u8) {
    Address::find_program_address(&[MINT, MINT_SEED], id())
}

#[cfg(not(debug_assertions))]
#[inline(always)]
pub fn mint_pda() -> (Address, u8) {
    (MINT_ADDRESS, MINT_BUMP)
}

#[cfg(debug_assertions)]
pub fn metadata_pda() -> (Address, u8) {
    let (mint, _) = mint_pda();

    Address::find_program_address(
        &[METADATA, metaplex::ID.as_ref(), mint.as_ref()],
        metaplex::ID,
    )
}

#[cfg(not(debug_assertions))]
#[inline(always)]
pub fn metadata_pda() -> (Address, u8) {
    (METADATA_ADDRESS, METADATA_BUMP)
}

#[cfg(debug_assertions)]
pub fn treasury_pda() -> (Address, u8) {
    Address::find_program_address(&[TREASURY], id())
}

#[cfg(not(debug_assertions))]
#[inline(always)]
pub fn treasury_pda() -> (Address, u8) {
    (TREASURY_ADDRESS, TREASURY_BUMP)
}


#[cfg(test)]
mod tests {
    use solana_program::pubkey::Pubkey;

    use super::*;

    #[test]
    fn test_pda_against_consts() {
        // These tests, as nonsensical as they seem, are to ensure that the PDAs generated by the
        // consts match the ones generated by the official functions. The consts are generated by
        // external deps, so if we straight up use the consts, we are trusting that the external
        // deps are working as expected, which is not a good idea. Always be testing.

        let (pda, bump) = mint_pda();
        assert_eq!(pda, MINT_ADDRESS);
        assert_eq!(bump, MINT_BUMP);

        let (pda, bump) = metadata_pda();
        assert_eq!(pda, METADATA_ADDRESS);
        assert_eq!(bump, METADATA_BUMP);

        let (pda, bump) = treasury_pda();
        assert_eq!(pda, TREASURY_ADDRESS);
        assert_eq!(bump, TREASURY_BUMP);
    }

    #[test]
    fn metadata_pda_matches_solana_derivation() {
        let (pda, bump) = metadata_pda();
        let (mint, _) = mint_pda();
        let (expected_pda, expected_bump) = Pubkey::find_program_address(
            &[METADATA, metaplex::ID.as_ref(), mint.as_ref()],
            &metaplex::ID,
        );

        assert_eq!(pda, expected_pda.into());
        assert_eq!(bump, expected_bump);
    }
}
