[package]
name = "tape-metrics"
version.workspace = true
edition.workspace = true
description = "Metrics infrastructure for Tapedrive"
license.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
readme.workspace = true

[features]
default = []
metrics = ["prometheus"]

[dependencies]
prometheus = { workspace = true, optional = true }

[target.'cfg(target_os = "linux")'.dependencies]
prometheus = { workspace = true, optional = true, features = ["process"] }
