[identity]
keypair_path = "~/.config/solana/id.json"

[solana]
rpc_url = "https://api.devnet.solana.com"
ws_url = "wss://api.devnet.solana.com/"
commitment = "confirmed"
priority_fee_lamports = 1000
max_tx_retries = 3

[storage]
rocksdb_primary_path = "./db_tapestore"
rocksdb_secondary_path = "./db_tapestore_secondary"
rocksdb_cache_size_mb = 512

[logging]
log_level = "info"
log_path = "./logs/tape.log"
metrics_interval = 30
