use crate::consts::*;
use tape_core::prelude::*;
use steel::*;

#[cfg(debug_assertions)]
pub fn system_pda() -> (Pubkey, u8) {
    Pubkey::find_program_address(&[SYSTEM], &crate::id())
}

#[cfg(not(debug_assertions))]
#[inline(always)]
pub fn system_pda() -> (Pubkey, u8) {
    (SYSTEM_ADDRESS, SYSTEM_BUMP)
}

#[cfg(debug_assertions)]
pub fn treasury_pda() -> (Pubkey, u8) {
    Pubkey::find_program_address(&[TREASURY], &crate::id())
}

#[cfg(not(debug_assertions))]
#[inline(always)]
pub fn treasury_pda() -> (Pubkey, u8) {
    (TREASURY_ADDRESS, TREASURY_BUMP)
}

#[cfg(debug_assertions)]
pub fn treasury_ata() -> (Pubkey, u8) {
    let (treasury_pda, _bump) = treasury_pda();
    let (mint_pda, _bump) = mint_pda();
    Pubkey::find_program_address(
        &[
            treasury_pda.as_ref(),
            spl_token::ID.as_ref(),
            mint_pda.as_ref(),
        ],
        &spl_associated_token_account::ID,
    )
}

#[cfg(not(debug_assertions))]
#[inline(always)]
pub fn treasury_ata() -> (Pubkey, u8) {
    (TREASURY_ATA, TREASURY_ATA_BUMP)
}

#[cfg(debug_assertions)]
pub fn archive_pda() -> (Pubkey, u8) {
    Pubkey::find_program_address(&[ARCHIVE], &crate::id())
}

#[cfg(not(debug_assertions))]
#[inline(always)]
pub fn archive_pda() -> (Pubkey, u8) {
    (ARCHIVE_ADDRESS, ARCHIVE_BUMP)
}

#[cfg(debug_assertions)]
pub fn epoch_pda() -> (Pubkey, u8) {
    Pubkey::find_program_address(&[EPOCH], &crate::id())
}

#[cfg(not(debug_assertions))]
#[inline(always)]
pub fn epoch_pda() -> (Pubkey, u8) {
    (EPOCH_ADDRESS, EPOCH_BUMP)
}

#[cfg(debug_assertions)]
pub fn mint_pda() -> (Pubkey, u8) {
    Pubkey::find_program_address(&[MINT, MINT_SEED], &crate::id())
}

#[cfg(not(debug_assertions))]
#[inline(always)]
pub fn mint_pda() -> (Pubkey, u8) {
    (MINT_ADDRESS, MINT_BUMP)
}

#[cfg(debug_assertions)]
pub fn metadata_pda() -> (Pubkey, u8) {
    let (mint, _) = mint_pda();
    Pubkey::find_program_address(
        &[METADATA, mpl_token_metadata::ID.as_ref(), mint.as_ref()],
        &mpl_token_metadata::ID,
    )
}

#[cfg(not(debug_assertions))]
#[inline(always)]
pub fn metadata_pda() -> (Pubkey, u8) {
    (METADATA_ADDRESS, METADATA_BUMP)
}

#[inline(always)]
pub fn exchange_pda(authority: Pubkey) -> (Pubkey, u8) {
    Pubkey::find_program_address(&[EXCHANGE, authority.as_ref()], &crate::id())
}

#[inline(always)]
pub fn exchange_ata(exchange: Pubkey) -> (Pubkey, u8) {
    let (mint_pda, _) = mint_pda();
    Pubkey::find_program_address(
        &[
            exchange.as_ref(), 
            spl_token::ID.as_ref(),
            mint_pda.as_ref()
        ],
        &spl_associated_token_account::ID,
    )
}

#[cfg(debug_assertions)]
pub fn candidate_pda() -> (Pubkey, u8) {
    Pubkey::find_program_address(&[CANDIDATE], &crate::id())
}

#[cfg(not(debug_assertions))]
#[inline(always)]
pub fn candidate_pda() -> (Pubkey, u8) {
    (CANDIDATE_ADDRESS, CANDIDATE_BUMP)
}

#[inline(always)]
pub fn committee_pda(epoch: EpochNumber) -> (Pubkey, u8) {
    Pubkey::find_program_address(&[COMMITTEE, &epoch.pack()], &crate::id())
}

#[inline(always)]
pub fn storage_node_pda(authority: Pubkey) -> (Pubkey, u8) {
    Pubkey::find_program_address(&[NODE, authority.as_ref()], &crate::id())
}

#[inline(always)]
pub fn staked_tape_pda(authority: Pubkey, node: Pubkey) -> (Pubkey, u8) {
    Pubkey::find_program_address(&[STAKE, authority.as_ref(), node.as_ref()], &crate::id())
}

#[inline(always)]
pub fn staked_tape_ata(stake: Pubkey) -> (Pubkey, u8) {
    let (mint_pda, _) = mint_pda();
    Pubkey::find_program_address(
        &[
            stake.as_ref(),
            spl_token::ID.as_ref(),
            mint_pda.as_ref(),
        ],
        &spl_associated_token_account::ID,
    )
}

#[inline(always)]
pub fn resource_pda(authority: Pubkey) -> (Pubkey, u8) {
    Pubkey::find_program_address(&[RESOURCE, authority.as_ref()], &crate::id())
}

#[inline(always)]
pub fn blob_pda(authority: Pubkey, hash: Hash) -> (Pubkey, u8) {
    Pubkey::find_program_address(&[BLOB, authority.as_ref(), hash.as_ref()], &crate::id())
}


#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_pda_against_consts() {
        // These tests, as nonsensical as they seem, are to ensure that the PDAs generated by the
        // consts match the ones generated by the official functions. The consts are generated by
        // external deps, so if we straight up use the consts, we are trusting that the external
        // deps are working as expected, which is not a good idea. Always be testing.
        
        let (pda, bump) = system_pda();
        assert_eq!(pda, SYSTEM_ADDRESS);
        assert_eq!(bump, SYSTEM_BUMP);

        let (pda, bump) = epoch_pda();
        assert_eq!(pda, EPOCH_ADDRESS);
        assert_eq!(bump, EPOCH_BUMP);

        let (pda, bump) = archive_pda();
        assert_eq!(pda, ARCHIVE_ADDRESS);
        assert_eq!(bump, ARCHIVE_BUMP);

        let (pda, bump) = mint_pda();
        assert_eq!(pda, MINT_ADDRESS);
        assert_eq!(bump, MINT_BUMP);

        let (pda, bump) = metadata_pda();
        assert_eq!(pda, METADATA_ADDRESS);
        assert_eq!(bump, METADATA_BUMP);

        let (pda, bump) = treasury_pda();
        assert_eq!(pda, TREASURY_ADDRESS);
        assert_eq!(bump, TREASURY_BUMP);

        let (pda, bump) = treasury_ata();
        assert_eq!(pda, TREASURY_ATA);
        assert_eq!(bump, TREASURY_ATA_BUMP);
    }
}
