use crate::declare_id;
use solana_program::pubkey::Pubkey;
use const_crypto::ed25519;
use tape_core::prelude::Hash;
use super::token::MINT_ADDRESS;

pub const MEMBER_COUNT: usize = 128;
pub const SEAT_COUNT: usize = 1000;
pub const FUTURE_EPOCHS: usize = 256;
pub const EPOCH_HISTORY: usize = 256;
pub const PENDING_VALUES: usize = 2;
pub const EPOCH_DURATION: i64 = 7 * 24 * 60 * 60 * 1000; // 1 week in milliseconds

declare_id!("tajZ1QndNonM3teK59PdUfiF9ZAQT6xqucipbs8mN8W"); 

pub const PROGRAM_ID: [u8; 32] = 
    unsafe { *(&id() as *const Pubkey as *const [u8; 32]) };

pub const SYSTEM:    &[u8] = b"system";
pub const ARCHIVE:   &[u8] = b"archive";
pub const EPOCH:     &[u8] = b"epoch";
pub const NODE:      &[u8] = b"node";
pub const RESOURCE:  &[u8] = b"resource";
pub const BLOB:      &[u8] = b"blob";

pub const SYSTEM_ADDRESS: Pubkey =
    Pubkey::new_from_array(ed25519::derive_program_address(&[SYSTEM], &PROGRAM_ID).0);

pub const SYSTEM_BUMP: u8 =
    ed25519::derive_program_address(&[SYSTEM], &PROGRAM_ID).1;

pub const EPOCH_ADDRESS: Pubkey =
    Pubkey::new_from_array(ed25519::derive_program_address(&[EPOCH], &PROGRAM_ID).0);

pub const EPOCH_BUMP: u8 =
    ed25519::derive_program_address(&[EPOCH], &PROGRAM_ID).1;

pub const ARCHIVE_ADDRESS: Pubkey =
    Pubkey::new_from_array(ed25519::derive_program_address(&[ARCHIVE], &PROGRAM_ID).0);

pub const ARCHIVE_BUMP: u8 =
    ed25519::derive_program_address(&[ARCHIVE], &PROGRAM_ID).1;

pub const ARCHIVE_ATA: Pubkey = Pubkey::new_from_array(
    ed25519::derive_program_address(
        &[
            unsafe { &*(&ARCHIVE_ADDRESS as *const Pubkey as *const [u8; 32]) },
            unsafe { &*(&spl_token::id() as *const Pubkey as *const [u8; 32]) },
            unsafe { &*(&MINT_ADDRESS as *const Pubkey as *const [u8; 32]) },
        ],
        unsafe { &*(&spl_associated_token_account::id() as *const Pubkey as *const [u8; 32]) },
    )
    .0,
);

pub const ARCHIVE_ATA_BUMP: u8 = 
    ed25519::derive_program_address(
        &[
            unsafe { &*(&ARCHIVE_ADDRESS as *const Pubkey as *const [u8; 32]) },
            unsafe { &*(&spl_token::id() as *const Pubkey as *const [u8; 32]) },
            unsafe { &*(&MINT_ADDRESS as *const Pubkey as *const [u8; 32]) },
        ],
        unsafe { &*(&spl_associated_token_account::id() as *const Pubkey as *const [u8; 32]) },
    )
    .1;

// ====================================================================
// PDA Functions
// ====================================================================

#[cfg(debug_assertions)]
pub fn system_pda() -> (Pubkey, u8) {
    Pubkey::find_program_address(&[SYSTEM], &id())
}

#[cfg(not(debug_assertions))]
#[inline(always)]
pub fn system_pda() -> (Pubkey, u8) {
    (SYSTEM_ADDRESS, SYSTEM_BUMP)
}

#[cfg(debug_assertions)]
pub fn epoch_pda() -> (Pubkey, u8) {
    Pubkey::find_program_address(&[EPOCH], &id())
}

#[cfg(not(debug_assertions))]
#[inline(always)]
pub fn epoch_pda() -> (Pubkey, u8) {
    (EPOCH_ADDRESS, EPOCH_BUMP)
}


#[cfg(debug_assertions)]
#[inline(always)]
pub fn archive_pda() -> (Pubkey, u8) {
    Pubkey::find_program_address(&[ARCHIVE], &id())
}

#[cfg(not(debug_assertions))]
#[inline(always)]
pub fn archive_pda() -> (Pubkey, u8) {
    (ARCHIVE_ADDRESS, ARCHIVE_BUMP)
}

#[cfg(debug_assertions)]
#[inline(always)]
pub fn archive_ata() -> (Pubkey, u8) {
    Pubkey::find_program_address(
        &[
            ARCHIVE_ADDRESS.as_ref(),
            spl_token::ID.as_ref(),
            MINT_ADDRESS.as_ref(),
        ],
        &spl_associated_token_account::ID,
    )
}

#[cfg(not(debug_assertions))]
#[inline(always)]
pub fn archive_ata() -> (Pubkey, u8) {
    (ARCHIVE_ATA, ARCHIVE_ATA_BUMP)
}


#[inline(always)]
pub fn node_pda(authority: Pubkey) -> (Pubkey, u8) {
    Pubkey::find_program_address(&[NODE, authority.as_ref()], &id())
}

#[inline(always)]
pub fn tape_pda(authority: Pubkey) -> (Pubkey, u8) {
    Pubkey::find_program_address(&[RESOURCE, authority.as_ref()], &id())
}

#[inline(always)]
pub fn blob_pda(authority: Pubkey, hash: Hash) -> (Pubkey, u8) {
    Pubkey::find_program_address(&[BLOB, authority.as_ref(), hash.as_ref()], &id())
}


#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_pda_against_consts() {
        // These tests, as nonsensical as they seem, are to ensure that the PDAs generated by the
        // consts match the ones generated by the official functions. The consts are generated by
        // external deps, so if we straight up use the consts, we are trusting that the external
        // deps are working as expected, which is not a good idea. Always be testing.
        
        let (pda, bump) = system_pda();
        assert_eq!(pda, SYSTEM_ADDRESS);
        assert_eq!(bump, SYSTEM_BUMP);

        let (pda, bump) = epoch_pda();
        assert_eq!(pda, EPOCH_ADDRESS);
        assert_eq!(bump, EPOCH_BUMP);

        let (pda, bump) = archive_pda();
        assert_eq!(pda, ARCHIVE_ADDRESS);
        assert_eq!(bump, ARCHIVE_BUMP);

        let (pda, bump) = archive_ata();
        assert_eq!(pda, ARCHIVE_ATA);
        assert_eq!(bump, ARCHIVE_ATA_BUMP);
    }
}
