use crate::declare_id;
use const_crypto::ed25519;
use solana_program::pubkey::Pubkey;

declare_id!("tape9hFAE7jstfKB2QT1ovFNUZKKtDUyGZiGQpnBFdL"); 

pub const PROGRAM_ID: [u8; 32] = 
    unsafe { *(&id() as *const Pubkey as *const [u8; 32]) };

pub const MINT:      &[u8] = b"mint";
pub const MINT_SEED: &[u8] = &[152, 68, 212, 200, 25, 113, 221, 71];
pub const METADATA:  &[u8] = b"metadata";

pub const TOKEN_DECIMALS: u8 = 6;
pub const ONE_TAPE: u64 = 10u64.pow(TOKEN_DECIMALS as u32);
pub const MAX_SUPPLY: u64 = 7_000_000_000 * ONE_TAPE;

pub const METADATA_NAME:   &str = "TAPE";
pub const METADATA_SYMBOL: &str = "TAPE";
pub const METADATA_URI:    &str = "https://tapedrive.io/metadata.json";

pub const MINT_ADDRESS: Pubkey =
    Pubkey::new_from_array(ed25519::derive_program_address(&[MINT, MINT_SEED], &PROGRAM_ID).0);

pub const MINT_BUMP: u8 = 
    ed25519::derive_program_address(&[MINT, MINT_SEED], &PROGRAM_ID).1;

pub const METADATA_ADDRESS: Pubkey = Pubkey::new_from_array(
    ed25519::derive_program_address(
        &[
            METADATA,
            unsafe { &*(&mpl_token_metadata::ID as *const Pubkey as *const [u8; 32]) },
            unsafe { &*(&MINT_ADDRESS as *const Pubkey as *const [u8; 32]) },
        ],
        unsafe { &*(&mpl_token_metadata::ID as *const Pubkey as *const [u8; 32]) },
    ).0
);

pub const METADATA_BUMP: u8 = ed25519::derive_program_address(
    &[
        METADATA,
        unsafe { &*(&mpl_token_metadata::ID as *const Pubkey as *const [u8; 32]) },
        unsafe { &*(&MINT_ADDRESS as *const Pubkey as *const [u8; 32]) },
    ],
    unsafe { &*(&mpl_token_metadata::ID as *const Pubkey as *const [u8; 32]) },
).1;


#[cfg(debug_assertions)]
pub fn mint_pda() -> (Pubkey, u8) {
    Pubkey::find_program_address(&[MINT, MINT_SEED], &id())
}

#[cfg(not(debug_assertions))]
#[inline(always)]
pub fn mint_pda() -> (Pubkey, u8) {
    (MINT_ADDRESS, MINT_BUMP)
}

#[cfg(debug_assertions)]
pub fn metadata_pda() -> (Pubkey, u8) {
    let (mint, _) = mint_pda();
    Pubkey::find_program_address(
        &[METADATA, mpl_token_metadata::ID.as_ref(), mint.as_ref()],
        &mpl_token_metadata::ID,
    )
}

#[cfg(not(debug_assertions))]
#[inline(always)]
pub fn metadata_pda() -> (Pubkey, u8) {
    (METADATA_ADDRESS, METADATA_BUMP)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_pda_against_consts() {
        // These tests, as nonsensical as they seem, are to ensure that the PDAs generated by the
        // consts match the ones generated by the official functions. The consts are generated by
        // external deps, so if we straight up use the consts, we are trusting that the external
        // deps are working as expected, which is not a good idea. Always be testing.

        let (pda, bump) = mint_pda();
        assert_eq!(pda, MINT_ADDRESS);
        assert_eq!(bump, MINT_BUMP);

        let (pda, bump) = metadata_pda();
        assert_eq!(pda, METADATA_ADDRESS);
        assert_eq!(bump, METADATA_BUMP);
    }
}
