[package]
name = "tape-program"
description.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true

documentation = "https://docs.rs/tape-program"

[lib]
crate-type = ["cdylib", "lib"]
name = "tape"

[features]
default = []
airdrop = []

[dependencies]
crankx.workspace = true
packx.workspace = true

mpl-token-metadata.workspace = true
tape-api.workspace = true
solana-program.workspace = true
spl-token.workspace = true
spl-associated-token-account.workspace = true
steel.workspace = true
brine-tree.workspace = true


# Fix for issues with `build-sbf` rustc being on `1.79-dev`
bytemuck_derive=">=1.8.1, <1.9.0"
half = "=2.4.1"

[dev-dependencies]
bincode = "1.3"
solana-sdk = "2.1.0"
litesvm = "0.5.0"
litesvm-token = "0.5.0"
pretty-hex = "0.4.1"
rand = "0.8.5"
solana-compute-budget = "2.1.16"
solana-client = "=2.1"
tokio = { version = "1.37", features = ["full"] }
chrono.workspace = true
sha2 = "0.10.9"
serde_json = "1.0.142"
serde.workspace = true
